import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
test('cooperation lifecycle preserves booking exclusivity, privacy, verified notifications and stable selection identity', async t => {
const root=fileURLToPath(new URL('../',import.meta.url));
const db=new PGlite(); t.after(()=>db.close());
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
insert into auth.users values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');`);
for(const name of ['202609240001_admin.sql','202609240002_client_galleries.sql','202609240004_inquiry_references.sql','202609240005_inquiry_workflow.sql','202609240006_shoot_availability.sql','202609240007_gallery_drafts.sql','202609240008_shoot_confirmations.sql','202610050001_inquiry_reference_lookup.sql','202610050002_portfolio_favorites.sql','202610050003_cooperation_center.sql']){
 try {await db.exec(await fs.readFile(root+'/supabase/migrations/'+name,'utf8'));}catch(e){throw e;}
}
await db.exec(await fs.readFile(root+'/supabase/migrations/202610050003_cooperation_center.sql','utf8'));
await db.exec(`insert into public.site_admins(user_id) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');set request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';`);
const q=async(sql,args=[])=>(await db.query(sql,args)).rows[0];
const payload={name:'Luna',contact_method:'Instagram',contact_account:'@test',collaboration_type:'主題合作',preferred_date:null,description:'Golden light',consent:true};
const submit=async(sid,hash)=>{const r=await q('select public.submit_workflow_inquiry($1::uuid,$2,$3,$4::jsonb) as value',[sid,hash,'c'.repeat(64),JSON.stringify(payload)]);return r.value;};
const one=await submit('11111111-1111-4111-8111-111111111111','a'.repeat(64));
const two=await submit('22222222-2222-4222-8222-222222222222','b'.repeat(64));
const id1=(await q('select inquiry_id from private.inquiry_receipts where reference=$1',[one.reference])).inquiry_id;
const id2=(await q('select inquiry_id from private.inquiry_receipts where reference=$1',[two.reference])).inquiry_id;
const open=async(ref,hash,session)=>(await q('select public.open_cooperation_center($1,$2,$3) as value',[ref,hash,session])).value;
let first=await open(one.reference,null,'1'.repeat(64));let second=await open(null,'b'.repeat(64),'2'.repeat(64));
assert.equal(first.center.version,0);assert.equal(second.reference,two.reference);
await assert.rejects(open('PHOX-00000000000000000000',null,'3'.repeat(64)),/forbidden/);
const mutate=async(hash,action,version,input={})=>(await q('select public.mutate_cooperation_center($1,$2,$3,$4::jsonb) as value',[hash,action,version,JSON.stringify(input)])).value;
const slot1=(await q("insert into public.shoot_availability(starts_at,ends_at) values(now()+interval '10 days',now()+interval '10 days 2 hours') returning id")).id;
const slot2=(await q("insert into public.shoot_availability(starts_at,ends_at) values(now()+interval '11 days',now()+interval '11 days 2 hours') returning id")).id;
first=await mutate('1'.repeat(64),'hold',0,{slotId:slot1});assert(first.center.hold);const expiry=first.center.hold.expiresAt;
first=await mutate('1'.repeat(64),'hold',first.center.version,{slotId:slot1});assert.equal(first.center.hold.expiresAt,expiry);
await assert.rejects(mutate('2'.repeat(64),'hold',0,{slotId:slot1}),/conflict/);
await assert.rejects(mutate('1'.repeat(64),'hold',first.center.version,{slotId:slot2}),/hold_change_wait/);
let publicSlots=(await q('select public.get_public_availability(current_date,current_date+20) as value')).value;
assert.equal(publicSlots.find(x=>x.id===slot1).status,'unavailable');
await assert.rejects(q('select public.admin_save_availability($1::uuid,1,now()+interval \'10 days\',now()+interval \'10 days 2 hours\',\'closed\')',[slot1]),/conflict/);
const publish=async(id,slot,version=0)=>(await q("select public.admin_update_shoot_confirmation($1::uuid,$2,'confirmed',$3::uuid,'Taipei','','shirt','water','indoors','2 weeks','discuss') as value",[id,version,slot])).value;
await assert.rejects(publish(id2,slot1),/conflict/);
await publish(id1,slot1);first=await mutate('1'.repeat(64),'read',0);assert(first.confirmation);assert.equal(first.center.hold,null);
first=await mutate('1'.repeat(64),'checklist',first.center.version,{checklist:{wardrobe:true,route:true}});assert.equal(first.center.checklist.wardrobe,true);
await assert.rejects(mutate('1'.repeat(64),'checklist',first.center.version-1,{checklist:{rest:true}}),/conflict/);
await assert.rejects(mutate('1'.repeat(64),'checklist',first.center.version,{checklist:{isAdmin:true}}),/invalid_input/);
first=await mutate('1'.repeat(64),'change',first.center.version,{preferredDate:'Next month',description:'change location'});assert(first.center.changeRequest);assert(first.confirmation);assert.equal(first.summary.description,'Golden light');
const gallery=(await q("insert into public.client_galleries(title,status) values('Test gallery','proofing') returning id")).id;
let admin=(await q("select public.admin_cooperation_center($1::uuid,'gallery',$2,$3::uuid) as value",[id1,first.center.version,gallery])).value;
assert.equal(admin.galleryId,gallery);first=admin;
first=await mutate('1'.repeat(64),'gallery',first.center.version,{hash:'4'.repeat(64)});
const inv1=(await q('select invite_id from private.cooperation_gallery_invites where inquiry_id=$1',[id1])).invite_id;
first=await mutate('1'.repeat(64),'gallery',first.center.version,{hash:'5'.repeat(64)});
assert.equal((await q('select invite_id from private.cooperation_gallery_invites where inquiry_id=$1',[id1])).invite_id,inv1);
assert.equal((await q('select (private.client_invite($1)).id as id',['4'.repeat(64)])).id,inv1);
await db.exec("update private.cooperation_gallery_sessions set expires_at=now()-interval '1 minute' where token_hash='"+'4'.repeat(64)+"'");
await assert.rejects(q("select private.client_invite($1)",['4'.repeat(64)]),/invalid_invitation/);
assert.equal((await q('select (private.client_invite($1)).id as id',['5'.repeat(64)])).id,inv1);
const photo=(await q("insert into public.client_gallery_photos(gallery_id,title,preview_path,approved) values($1::uuid,'Photo',$2,true) returning id",[gallery,gallery+'/photo.webp'])).id;
await q("select public.client_save_draft($1,$2::uuid[],'{}'::jsonb,'note',0)",['5'.repeat(64),[photo]]);
await q("select public.client_confirm_selection($1,$2::uuid[],'note','{}'::jsonb,1)",['5'.repeat(64),[photo]]);
first=await mutate('1'.repeat(64),'gallery',first.center.version,{hash:'6'.repeat(64)});
const restored=(await q('select public.client_read_gallery($1) as value',['6'.repeat(64)])).value;
assert.equal(restored.selection.photo_ids[0],photo);
assert.equal(first.center.gallery.selectedCount,1);
await assert.rejects(q("select public.client_confirm_selection($1,$2::uuid[],'changed','{}'::jsonb,1)",['6'.repeat(64),[photo]]),/conflict/);
first=await mutate('1'.repeat(64),'email',first.center.version,{email:'test@example.test',hash:'d'.repeat(64),code:'123456'});
for(let t=0;t<5;t++)first=await mutate('1'.repeat(64),'verifyEmail',first.center.version,{hash:'0'.repeat(64)});
first=await mutate('1'.repeat(64),'verifyEmail',first.center.version,{hash:'d'.repeat(64)});assert.equal(first.center.notifications.email,false);
await db.exec("update private.cooperation_centers set email_requested_at=now()-interval '6 minutes',email_attempts=0 where inquiry_id='"+id1+"'");
first=await mutate('1'.repeat(64),'verifyEmail',first.center.version,{hash:'d'.repeat(64)});assert.equal(first.center.notifications.email,true);
first=await mutate('1'.repeat(64),'lineLink',first.center.version,{hash:'e'.repeat(64)});
assert.equal((await q("select public.bind_cooperation_line($1,$2) as linked",['e'.repeat(64),'U'+'f'.repeat(32)])).linked,true);
assert.equal((await q("select public.bind_cooperation_line($1,$2) as linked",['e'.repeat(64),'U'+'0'.repeat(32)])).linked,false);
first=await mutate('1'.repeat(64),'read',0);
await db.exec("update public.collaboration_requests set status='contacted' where id='"+id1+"'");
first=await mutate('1'.repeat(64),'read',0);
const lease='33333333-3333-4333-8333-333333333333';
const jobs=(await q('select public.claim_cooperation_notifications($1::text[],$2::uuid) as value',[['email','line'],lease])).value;assert(jobs.length>=4);
const again=(await q('select public.claim_cooperation_notifications($1::text[],$2::uuid) as value',[['email','line'],'44444444-4444-4444-8444-444444444444'])).value;assert.equal(again.length,0);
await q('select public.complete_cooperation_notification($1::uuid,$2::uuid,true,null)',[jobs[0].id,lease]);
assert.equal((await q('select state from private.notification_outbox where id=$1',[jobs[0].id])).state,'sent');
first=await mutate('1'.repeat(64),'cancel',first.center.version,{confirm:true});assert(first.center.cancelledAt);assert.equal(first.confirmation,null);assert.equal(first.status,'closed');
assert.equal((await q('select status from public.shoot_availability where id=$1',[slot1])).status,'open');
await assert.rejects(publish(id1,slot2),/cancelled/);
await assert.rejects(q('select private.client_invite($1)',['5'.repeat(64)]),/invalid_invitation/);
second=await mutate('2'.repeat(64),'hold',0,{slotId:slot1});
await db.exec("update private.cooperation_holds set expires_at=now()-interval '1 minute' where inquiry_id='"+id2+"'");
publicSlots=(await q('select public.get_public_availability(current_date,current_date+20) as value')).value;assert.equal(publicSlots.find(x=>x.id===slot1).status,'open');
assert.equal((await mutate('2'.repeat(64),'read',0)).center.hold,null);
await db.exec("update private.inquiry_receipts set revoked_at=now() where inquiry_id='"+id2+"'");
await assert.rejects(mutate('2'.repeat(64),'read',0),/forbidden/);
for(const signature of ['open_cooperation_center(text,text,text)','mutate_cooperation_center(text,text,integer,jsonb)','bind_cooperation_line(text,text)','claim_cooperation_notifications(text[],uuid)'])assert.equal((await q("select has_function_privilege('anon',$1,'execute') as allowed",[signature])).allowed,false);
assert.equal((await q("select has_function_privilege('authenticated','admin_cooperation_center(uuid,text,integer,uuid)','execute') as allowed")).allowed,true);
});
